[build]
  command = "npm run build:netlify"
  publish = "dist/banderas_nila_lopez/browser"
  ignore = "exit 0"

[build.environment]
  NODE_VERSION = "20"

# Disable the Angular runtime plugin
[[plugins]]
  package = "@netlify/angular-runtime"

  [plugins.inputs]
    disable = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
